---
title: "Twitter Analysis"
author: "Eli & Sylvester"
date: "03/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo    = TRUE,
    message = FALSE, 
    warning = FALSE
)
```


```{r}
library(rtweet)
library(leaflet)
library(tmaptools)
library(tidygeocoder)
library(tidyverse)
```


```{r}
token <- create_token(
  app = Sys.getenv("app"),
  consumer_key =  Sys.getenv("key"),
  consumer_secret = Sys.getenv("secret"),
  access_token = Sys.getenv("access_token"),
  access_secret = Sys.getenv("access_secret")
  
)
```


```{r}
# geocode function for tweets 
geocode_EK <- function(loc, mil) {
  geo_loc <- tidygeocoder::geo(loc, method = 'osm', lat = latitude, long = longitude)
  paste0(paste0(paste0(geo_loc$latitude[1], ","), paste0(geo_loc$longitude[1], ",")),
         paste0(mil, "mi"))
  
}
```


```{r}
geocode_EK("london, uk", 100)
```


```{r}
st <- search_tweets(
  q = "#covid19",
  n = 300,
  include_rts = FALSE,
  lang = "en",
  geocode = geocode_EK("london, uk", 100)
)
```


```{r}
st %>% glimpse()
```


```{r}
st %>% 
  select(contains("coords")) %>% 
  unnest_wider(geo_coords) %>% 
  filter(!is.na(...1))
```


```{r}
st %>% 
  select(screen_name, text, coords_coords) %>% 
  unnest_wider(coords_coords) %>% 
  filter(!is.na(...1)) %>% 
  set_names(c("screen_name", "text", "lon", "lat")) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers(~lon, ~lat, popup = ~as.character(text), label = ~as.character(screen_name))
```


```{r}
data_prepared <- tibble(
  location = geocode_EK("london, uk", 100)
) %>% 
  separate(location, into = c("lat", "lon", "distance"), sep = ",", remove = FALSE) %>% 
  mutate(distance =  distance %>% str_remove_all("[^0-9.-]")) %>% 
  mutate_at(.vars = vars(-location), as.numeric)

data_prepared %>% 
  leaflet() %>% 
  setView(data_prepared$lon, data_prepared$lat, zoom = 3) %>% 
  addTiles() %>% 
  addMarkers(~lon, ~lat, popup = ~as.character(location), label = ~as.character(location)) %>% 
  addCircles(lng = ~lon, lat = ~lat, weight = 1, radius = ~distance/0.000621371)
  
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


```{r}

```


